#!/usr/bin/env bash
set -eu

host=${1:-}
name=pointless.services
if [ -z "$host" ]; then
  echo "Usage: ${BASH_SOURCE[0]} <host>"
  exit
fi
eval $(docker-machine env $host)
docker build -t $name-whisp .
docker rm -f $name || :
docker run -d --restart always --name $name \
  -p 127.0.0.1::80 \
  -e VIRTUAL_HOST=pointless.services \
  -e LETSENCRYPT_HOST=pointless.services \
  -e LETSENCRYPT_EMAIL=joshwillik@gmail.com \
  $name-whisp
